-- MySQL Script generated by MySQL Workbench
-- 10/12/16 19:00:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema frello
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema frello
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `frello` DEFAULT CHARACTER SET utf8 ;
USE `frello` ;

-- -----------------------------------------------------
-- Table `frello`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frello`.`user` (
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` CHAR(128) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frello`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frello`.`board` (
  `id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frello`.`user_board_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frello`.`user_board_access` (
  `user_email` VARCHAR(255) NOT NULL,
  `board_id` BIGINT UNSIGNED NOT NULL,
  `access` ENUM('OWNER', 'USER', 'VISITOR') NULL,
  PRIMARY KEY (`user_email`, `board_id`),
  INDEX `fk_user_has_board_board1_idx` (`board_id` ASC),
  INDEX `fk_user_has_board_user_idx` (`user_email` ASC),
  CONSTRAINT `fk_user_board_access_user`
    FOREIGN KEY (`user_email`)
    REFERENCES `frello`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_board_access_board`
    FOREIGN KEY (`board_id`)
    REFERENCES `frello`.`board` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `frello`;

DELIMITER $$
USE `frello`$$
CREATE TRIGGER `frello`.`board_BEFORE_INSERT`
BEFORE INSERT
   ON board FOR EACH ROW
BEGIN
	SET new.id = UUID_SHORT();
END;$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
